### ISSUE TITLE
How to quickly synchronize blocks?

### ISSUE THREAD

**Issue by l-yp** [spectre-project/rusty-spectre#14]
![Screenshot_20240820_131042-1](https://github.com/user-attachments/assets/35f7d6a7-3b29-4f20-90a9-146a82d257e3)
What should I do if the sync still fails after a day?

**Comment by duythien** [comment]
@l-yp There is noway to quick sync at the moment, to fix temp you can do something like this
```
mkdir -p ~/.rusty-spectre/spectre-mainnet/
cd ~/.rusty-spectre/spectre-mainnet/
wget https://spectredbase.com/datadir.zip
unzip datadir.zip
rm datadir.zip
```

**Comment by 0xA001113** [comment]
@l-yp You have time deviation. Please adjust local clock, ideally using `ntpdate`, `chrony`, `timedatectl` or any other OS tool for it.
